CREATE DATABASE dbGender;

CREATE table tblGender(
id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20) NOT NULL,
age INT,
gender VARCHAR(20) NOT NULL
);
INSERT INTO tblGender (first_name,last_name,age,gender) VALUES
('Juan', 'Dela Cruz', 25, 'Male'),
('Maria', 'Santos', 30, 'Female'),
('Jose', 'Rizal', 35, 'Male'),
('Ana', 'Reyes', 22, 'Female'),
('Carlos', 'Gonzales', 28, 'Male'),
('Sofia', 'Martinez', 27, 'Female'),
('Miguel', 'Lopez', 40, 'Male'),
('Isabel', 'Torres', 33, 'Female'),
('Ramon', 'Fernandez', 29, 'Male'),
('Elena', 'Gutierrez', 31, 'Female'),
('Diego', 'Castro', 26, 'Male'),
('Carmen', 'Vargas', 37, 'Female'),
('Antonio', 'Navarro', 32, 'Male'),
('Lucia', 'Dominguez', 24, 'Female'),
('Pedro', 'Mendoza', 27, 'Male'),
('Gabriela', 'Del Rosario', 29, 'Female'),
('Fernando', 'Aguilar', 38, 'Male'),
('Patricia', 'Ramirez', 26, 'Female'),
('Andres', 'Santiago', 34, 'Male'),
('Veronica', 'Ortiz', 23, 'Female'),
('Hector', 'Bautista', 39, 'Male'),
('Teresa', 'Silva', 25, 'Female'),
('Luis', 'Morales', 31, 'Male'),
('Angela', 'Pineda', 28, 'Female'),
('Emilio', 'Valdez', 36, 'Male'),
('Beatriz', 'Fuentes', 27, 'Female'),
('Oscar', 'Jimenez', 30, 'Male'),
('Diana', 'Mendez', 29, 'Female'),
('Ricardo', 'Cruz', 33, 'Male'),
('Julia', 'Lozano', 35, 'Female'),
('Esteban', 'Delgado', 37, 'Male'),
('Natalia', 'Ramos', 32, 'Female'),
('Javier', 'Salazar', 28, 'Male'),
('Rosa', 'Escobar', 30, 'Female'),
('Victor', 'Peralta', 40, 'Male'),
('Mariana', 'Cortez', 23, 'Female'),
('Alfonso', 'Nunez', 26, 'Male'),
('Celeste', 'Ibanez', 34, 'Female'),
('Eduardo', 'Estrada', 38, 'Male'),
('Lourdes', 'Guerrero', 27, 'Female'),
('Salvador', 'Cabrera', 31, 'Male'),
('Elisa', 'Flores', 24, 'Female'),
('Roberto', 'Vega', 39, 'Male'),
('Andrea', 'Munoz', 25, 'Female'),
('Francisco', 'Rivera', 37, 'Male'),
('Clara', 'Hernandez', 26, 'Female'),
('Gustavo', 'Pascual', 30, 'Male'),
('Monica', 'Miranda', 29, 'Female'),
('Enrique', 'Fernandez', 28, 'Male');


